export const SET_POPUPS = 'SET_POPUPS' 
export const REMOVE_POPUP = 'REMOVE_POPUP'

export const SUBMIT_ATTEMPT = 'SUBMIT_ATTEMPT'

export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'